/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiView;

import buisnessLogic.KontaktiInterface;
import buisnessLogic.KontaktiRepository;
import database.Kontakti;
import database.Pacienti;
import java.util.List;


public class KontaktiFrame extends javax.swing.JInternalFrame {
    Pacienti p;
    KontaktiInterface kontaktiInterface = new KontaktiRepository();
    int KontaktiID;
    
    public KontaktiFrame(Pacienti P) {
        initComponents();
        this.p = P;
        emriPacienti.setText(P.getEmri() + "   " +P.getMbiemri()); 
        listKontakti();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        tel1TextField = new javax.swing.JTextField();
        tel2TextField = new javax.swing.JTextField();
        tel1Label = new javax.swing.JLabel();
        tel2Label = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        createButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        emriPacienti = new javax.swing.JLabel();
        tel1 = new javax.swing.JLabel();
        tel2 = new javax.swing.JLabel();
        email = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        tel1TextField.setForeground(new java.awt.Color(63, 63, 63));
        tel1TextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(63, 63, 63), 2));
        tel1TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tel1TextFieldActionPerformed(evt);
            }
        });

        tel2TextField.setForeground(new java.awt.Color(63, 63, 63));
        tel2TextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(63, 63, 63), 2));

        tel1Label.setText("Tel 1:");

        tel2Label.setText("Tel 2:");

        emailLabel.setText("E-mail :");

        emailTextField.setForeground(new java.awt.Color(63, 63, 63));
        emailTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(63, 63, 63), 2));

        createButton.setText("Create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Pacienti");

        emriPacienti.setText("jLabel3");

        tel1.setText("jLabel1");

        tel2.setText("jLabel4");

        email.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(emriPacienti))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tel2Label)
                                    .addComponent(emailLabel)
                                    .addComponent(tel1Label))
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tel2TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                    .addComponent(emailTextField)
                                    .addComponent(tel1TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(createButton)
                                .addGap(18, 18, 18)
                                .addComponent(editButton)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tel1)
                            .addComponent(tel2)
                            .addComponent(email))))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tel1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tel1Label)
                            .addComponent(tel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tel2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tel2Label)
                            .addComponent(tel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailLabel)
                            .addComponent(email)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(emriPacienti))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editButton)
                    .addComponent(createButton))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tel1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tel1TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tel1TextFieldActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        Kontakti k = new Kontakti();
        k.setEmail(emailTextField.getText());
        k.setNrtel1(tel1TextField.getText());
        k.setNrtel2(tel2TextField.getText());
        k.setPacientiID(p);
        kontaktiInterface.create(k);
        listKontakti();
    }//GEN-LAST:event_createButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        Kontakti k = new Kontakti();
        k.setEmail(emailTextField.getText());
        k.setNrtel1(tel1TextField.getText());
        k.setNrtel2(tel2TextField.getText());
        k.setPacientiID(p);
        k.setKontaktiid(KontaktiID);
        kontaktiInterface.delete(k);
        listKontakti();
        clearFields();  
    }//GEN-LAST:event_editButtonActionPerformed
    private void clearFields()
    {
        tel1TextField.setText("");
        tel2TextField.setText("");
        emailTextField.setText("");
    }
    private void listKontakti()
    {
       List<Kontakti> list = kontaktiInterface.findAll();
       for(int i = 0; i< list.size(); i++)
       {
        if(list.get(i).getPacientiID().equals(p))
        {
            Kontakti k = list.get(i);
            KontaktiID = k.getKontaktiid();
            tel1.setText(k.getNrtel1());
            tel2.setText(k.getNrtel2());
            email.setText(k.getEmail());
        }
        else
        {
            tel1.setText("Ska te dhena");
            tel2.setText("Ska te dhena");
            email.setText("Ska te dhena");
        }
       }
    }
            

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createButton;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel email;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel emriPacienti;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel tel1;
    private javax.swing.JLabel tel1Label;
    private javax.swing.JTextField tel1TextField;
    private javax.swing.JLabel tel2;
    private javax.swing.JLabel tel2Label;
    private javax.swing.JTextField tel2TextField;
    // End of variables declaration//GEN-END:variables
}
